# Fitxer: dockerfile_gsx_prac1
# vim: syntax=dockerfile
FROM gsx:prac3
# Instalar paquetes adicionales
RUN echo "deb https://deb.debian.org/debian/ bullseye non-free" > /etc/apt/sources.list.d/non-free.list \
    && apt update \
    && apt-get install -y --no-install-recommends \
    rsyslog \
    snmp \
    snmpd \
    snmp-mibs-downloader

# Copiar y aplicar parche para MIB
COPY SNMPv2-PDU.diff /root
RUN patch /usr/share/snmp/mibs/ietf/SNMPv2-PDU </root/SNMPv2-PDU.diff
