# Fitxer: fichero_crear_contenedores
# vim: syntax=dockerfile
FROM debian:bullseye-slim
MAINTAINER Adrian_GSX
RUN apt update
RUN apt-get install -y --no-install-recommends \
dnsutils ifupdown iproute2 iptables iputils-ping isc-dhcp-client nano procps rsyslog tcpdump
COPY ./GSX_Red.tgz /root
WORKDIR /root
RUN tar -xzf GSX_Red.tgz