# Fitxer: fichero_crear_contenedores
FROM debian:buster-slim
MAINTAINER Adrian_GSX
RUN apt update
RUN apt-get install -y --no-install-recommends \
dnsutils iproute2 iptables iputils-ping procps tcpdump \
initscripts quagga-ripd iputils-ping traceroute
WORKDIR /root
ADD ./prac7_config_rip.sh /root
CMD [ "/bin/bash" ]
